version: '2.2'
services:
  kibana:
    image: kibana:7.8.1
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: es7_01
    environment:
      - cluster.name=elastic
      - node.name=es7_01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_01
      - cluster.initial_master_nodes=es7_01
    volumes:
      - es7data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  es7data1:
    driver: local